language: ruby
rvm:
- 2.3.0
- 2.4.0

before_install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update -q
  - sudo apt-get install -y libsodium-dev

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake spec

cache: bundler

services:
  - postgresql

addons:
  postgresql: "9.6"
