language: ruby
rvm:
- 2.3.0
- 2.4.0
- jruby-19mode
- rbx-2

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
